# Generated by Django 3.2.8 on 2021-12-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik_username', models.CharField(max_length=11)),
                ('korisnik_ime', models.CharField(max_length=20)),
                ('korisnik_prezime', models.CharField(max_length=20)),
                ('korisnik_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kukac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kukac_vrsta', models.CharField(max_length=100)),
                ('kukac_porodica', models.CharField(max_length=100)),
                ('kukac_red', models.CharField(max_length=100)),
                ('kukac_datum_sakupljanja', models.DateField()),
                ('kukac_lokalitet', models.CharField(max_length=100)),
                ('kukac_duljina', models.CharField(max_length=20)),
                ('kukac_spol', models.BooleanField()),
                ('kukac_opis', models.TextField()),
                ('kukac_lovac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.korisnik')),
            ],
        ),
    ]
