# Generated by Django 3.2.8 on 2021-12-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kukac',
            name='kukac_spol',
            field=models.CharField(max_length=1),
        ),
    ]
