# Generated by Django 3.2.8 on 2022-02-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kukac_kukac_dostupan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='korisnik_ime',
            new_name='_ime',
        ),
        migrations.RenameField(
            model_name='korisnik',
            old_name='korisnik_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='korisnik',
            old_name='korisnik_prezime',
            new_name='prezime',
        ),
        migrations.RenameField(
            model_name='korisnik',
            old_name='korisnik_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_datum_sakupljanja',
            new_name='datum_sakupljanja',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_dostupan',
            new_name='dostupan',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_duljina',
            new_name='duljina',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_lokalitet',
            new_name='lokalitet',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_lovac',
            new_name='lovac',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_opis',
            new_name='opis',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_porodica',
            new_name='porodica',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_red',
            new_name='red',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_spol',
            new_name='spol',
        ),
        migrations.RenameField(
            model_name='kukac',
            old_name='kukac_vrsta',
            new_name='vrsta',
        ),
    ]
