# Generated by Django 3.2.8 on 2022-02-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220209_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='_ime',
            new_name='ime',
        ),
    ]
