# Generated by Django 3.2.8 on 2022-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename__ime_korisnik_ime'),
    ]

    operations = [
        migrations.AddField(
            model_name='kukac',
            name='slika',
            field=models.ImageField(default='0', upload_to=''),
        ),
    ]
