# Generated by Django 3.2.8 on 2022-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_korisnik_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='slika_profila',
            field=models.ImageField(default='0', upload_to='images/'),
        ),
    ]
