# Generated by Django 3.2.8 on 2022-02-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220219_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kukac',
            name='izbrisi',
        ),
        migrations.RemoveField(
            model_name='kukac',
            name='uredi',
        ),
    ]
