# Generated by Django 3.2.8 on 2022-02-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220219_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kukac',
            name='datum_sakupljanja',
        ),
        migrations.RemoveField(
            model_name='kukac',
            name='dostupan',
        ),
    ]
