# Generated by Django 3.2.8 on 2022-02-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_kukac_lovac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
