# Generated by Django 3.2.8 on 2022-02-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_korisnik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kukac',
            name='lovac',
        ),
    ]
