# Generated by Django 3.2.8 on 2022-02-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_kukac_lovac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kukac',
            name='lovac',
        ),
    ]
