# Generated by Django 3.2.8 on 2022-02-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_kukac_lovac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kukac',
            name='duljina',
            field=models.CharField(max_length=2),
        ),
    ]
