# Generated by Django 4.1.4 on 2023-02-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_kukac_lovac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kukac',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
